### ISSUE TITLE
ScriptValidate Evaluation unable to find NER tool

### ISSUE THREAD

**Issue by VarmaHub** [VarmaHub/FOX#7]
**Italian NER** tools:

![ner tools](https://user-images.githubusercontent.com/17321286/35488794-5b7405ae-048e-11e8-8356-3963200d2f8e.JPG)

**Terminal**:

![bash script validate](https://user-images.githubusercontent.com/17321286/35488762-d551d8c0-048d-11e8-9fa4-0e795cca0030.JPG)

**Log** Report:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building FOX 2.4.0
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for ca.uottawa:balie:jar:1.81.0 is missing, no dependency information available
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:java (default-cli) @ fox ---
28/Jan/201823:24:20  INFO [org.aksw.fox.ui.FoxCLI.main()] (FoxCLI.java:main:47) - Fox cl service starting ...
28/Jan/201823:24:20  INFO [org.aksw.fox.ui.FoxCLI.main()] (FoxCfg.java:loadFile:34) - Loads cfg ...
28/Jan/201823:24:20  INFO [org.aksw.fox.ui.FoxCLI.main()] (FoxCLI.java:main:110) - [/mnt/d/Masters/Subjects/Knowledge Graph/KG_Mini Project/Fox_Italian/input/Wikiner/aij-wikiner-it-wp3.bz2]
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/mnt/c/Users/Varma/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.6.1/log4j-slf4j-impl-2.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/mnt/c/Users/Varma/.m2/repository/org/slf4j/slf4j-log4j12/1.7.7/slf4j-log4j12-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
28/Jan/201823:24:22  INFO [org.aksw.fox.ui.FoxCLI.main()] (ToolsGenerator.java:init:76) - disambiguationTools:{it=org.aksw.fox.tools.linking.it.AgdistisDirectIT}
28/Jan/201823:24:22  INFO [org.aksw.fox.ui.FoxCLI.main()] (ToolsGenerator.java:init:77) - nerTools{it=[org.aksw.fox.tools.ner.it.SpotlightIT, org.askw.fox.tools.ner.it.TintNER]}
28/Jan/201823:24:22  INFO [org.aksw.fox.ui.FoxCLI.main()] (FoxClassifier.java:<init>:52) - class org.aksw.fox.nerlearner.FoxClassifier ...
28/Jan/201823:24:22  INFO [org.aksw.fox.ui.FoxCLI.main()] (Tools.java:<init>:59) - org.aksw.fox.tools.Tools ...
28/Jan/201823:24:22  INFO [org.aksw.fox.ui.FoxCLI.main()] (Tools.java:<init>:60) - tools list[org.aksw.fox.tools.ner.it.SpotlightIT, org.askw.fox.tools.ner.it.TintNER]
28/Jan/201823:24:22  INFO [org.aksw.fox.ui.FoxCLI.main()] (FoxCfg.java:getClass:91) - Loading class: org.aksw.fox.tools.ner.it.SpotlightIT
28/Jan/201823:24:22  INFO [org.aksw.fox.ui.FoxCLI.main()] (FoxCfg.java:getClass:91) - Loading class: org.askw.fox.tools.ner.it.TintNER
28/Jan/201823:24:22 ERROR [org.aksw.fox.ui.FoxCLI.main()] (FoxCfg.java:getClass:102) - org.askw.fox.tools.ner.it.TintNER
java.lang.ClassNotFoundException: org.askw.fox.tools.ner.it.TintNER
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at org.aksw.fox.utils.FoxCfg.getClass(FoxCfg.java:95)
	at org.aksw.fox.tools.Tools.<init>(Tools.java:66)
	at org.aksw.fox.tools.ToolsGenerator.getNERTools(ToolsGenerator.java:90)
	at org.aksw.fox.ui.FoxCLI.validate(FoxCLI.java:141)
	at org.aksw.fox.ui.FoxCLI.main(FoxCLI.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
28/Jan/201823:24:22 ERROR [org.aksw.fox.ui.FoxCLI.main()] (FoxCLI.java:validate:154) - Could not load class: org.askw.fox.tools.ner.it.TintNER
org.aksw.fox.data.exception.LoadingNotPossibleException: Could not load class: org.askw.fox.tools.ner.it.TintNER
	at org.aksw.fox.utils.FoxCfg.getClass(FoxCfg.java:103)
	at org.aksw.fox.tools.Tools.<init>(Tools.java:66)
	at org.aksw.fox.tools.ToolsGenerator.getNERTools(ToolsGenerator.java:90)
	at org.aksw.fox.ui.FoxCLI.validate(FoxCLI.java:141)
	at org.aksw.fox.ui.FoxCLI.main(FoxCLI.java:122)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
28/Jan/201823:24:22  INFO [org.aksw.fox.ui.FoxCLI.main()] (FoxCLI.java:main:129) - Fox cl service ended.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 22.584 s
[INFO] Finished at: 2018-01-28T23:24:22Z
[INFO] Final Memory: 31M/353M
[INFO] ------------------------------------------------------------------------

```

**Comment by VarmaHub** [comment]
Fixed. 30243858b484ab6d264f09def54ab591ad3fec14
